[package]
name = "opc-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.5"
openssl = "0.10"
opcua = { version = "0.11", features = ["client", "console-logging"] }